CREATE USER Administrador WITH PASSWORD '123456';
CREATE USER Recepcao WITH PASSWORD '123123';

GRANT ALL PRIVILEGES ON DATABASE BDClinica TO Administrador;
GRANT CONNECT ON DATABASE BDClinica TO Recepcao;

GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO Recepcao;
