CREATE USER administrador WITH PASSWORD '123456';
CREATE USER recepcao WITH PASSWORD '123123';
CREATE USER leitor WITH PASSWORD '123';

GRANT ALL PRIVILEGES ON DATABASE nomedobanco TO administrador;
GRANT CONNECT ON DATABASE nomedobanco TO recepcao;
GRANT CONNECT ON DATABASE nomedobanco TO leitor;

GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO recepcao;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO leitor;
